 
#ifndef _KSYNC_DEFINES_H_
#define _KSYNC_DEFINES_H_


#define SYNC_PREF_LOCAL 0
#define SYNC_PREF_REMOTE 1
#define SYNC_PREF_NEWEST 2
#define SYNC_PREF_ASK 3
#define SYNC_PREF_FORCE_LOCAL 4
#define SYNC_PREF_FORCE_REMOTE 5
#define SYNC_PREF_TAKE_BOTH 6

#define SYNC_MODE_NORMAL 0
#define SYNC_MODE_EXTERNAL 1

#define SYNC_TEMPSTATE_INITIAL 0
#define SYNC_TEMPSTATE_ADDED_EXTERNAL -1
#define SYNC_TEMPSTATE_NEW_EXTERNAL  -2
#define SYNC_TEMPSTATE_DELETE -3
#define SYNC_TEMPSTATE_NEW_ID -4
#define SYNC_TEMPSTATE_NEW_CSUM -5


#endif
